
project_id     = "cns-ai-engine-poc"
region        = "us-central1"
zone          = "us-central1-f"
instance_name = "sionna-vm-gpu"
machine_type  = "a2-highgpu-1g"
vpc_network   = "ai-engine-vpc"
subnet        = "ai-engine-mvp-cluster-subnet"
image_project  = "deeplearning-platform-release"
image_family = "pytorch-2-7-cu128-ubuntu-2204-nvidia-570"
ssh_tag        = "sionna-vm-gpu"
startup_script = "ai-training-vm-startup-script.sh"
storage_type = "pd-ssd"
gpu_type = "nvidia-tesla-a100"
gpu_count = "1"
